[
  { "img": "https://flagpedia.net/data/flags/w702/af.png", "name": "أفغانستان" },
  { "img": "https://flagpedia.net/data/flags/w702/al.png", "name": "ألبانيا" },
  { "img": "https://flagpedia.net/data/flags/w702/dz.png", "name": "الجزائر" },
  { "img": "https://flagpedia.net/data/flags/w702/ad.png", "name": "أندورا" },
  { "img": "https://flagpedia.net/data/flags/w702/ao.png", "name": "أنغولا" },
  { "img": "https://flagpedia.net/data/flags/w702/ar.png", "name": "الأرجنتين" },
  { "img": "https://flagpedia.net/data/flags/w702/am.png", "name": "أرمينيا" },
  { "img": "https://flagpedia.net/data/flags/w702/au.png", "name": "أستراليا" },
  { "img": "https://flagpedia.net/data/flags/w702/at.png", "name": "النمسا" },
  { "img": "https://flagpedia.net/data/flags/w702/az.png", "name": "أذربيجان" },

  { "img": "https://flagpedia.net/data/flags/w702/bh.png", "name": "البحرين" },
  { "img": "https://flagpedia.net/data/flags/w702/bd.png", "name": "بنغلاديش" },
  { "img": "https://flagpedia.net/data/flags/w702/by.png", "name": "بيلاروسيا" },
  { "img": "https://flagpedia.net/data/flags/w702/be.png", "name": "بلجيكا" },
  { "img": "https://flagpedia.net/data/flags/w702/bo.png", "name": "بوليفيا" },
  { "img": "https://flagpedia.net/data/flags/w702/ba.png", "name": "البوسنة والهرسك" },
  { "img": "https://flagpedia.net/data/flags/w702/br.png", "name": "البرازيل" },
  { "img": "https://flagpedia.net/data/flags/w702/bg.png", "name": "بلغاريا" },
  { "img": "https://flagpedia.net/data/flags/w702/kh.png", "name": "كمبوديا" },
  { "img": "https://flagpedia.net/data/flags/w702/cm.png", "name": "الكاميرون" },

  { "img": "https://flagpedia.net/data/flags/w702/ca.png", "name": "كندا" },
  { "img": "https://flagpedia.net/data/flags/w702/cl.png", "name": "تشيلي" },
  { "img": "https://flagpedia.net/data/flags/w702/cn.png", "name": "الصين" },
  { "img": "https://flagpedia.net/data/flags/w702/co.png", "name": "كولومبيا" },
  { "img": "https://flagpedia.net/data/flags/w702/cr.png", "name": "كوستاريكا" },
  { "img": "https://flagpedia.net/data/flags/w702/hr.png", "name": "كرواتيا" },
  { "img": "https://flagpedia.net/data/flags/w702/cu.png", "name": "كوبا" },
  { "img": "https://flagpedia.net/data/flags/w702/cy.png", "name": "قبرص" },
  { "img": "https://flagpedia.net/data/flags/w702/cz.png", "name": "التشيك" },
  { "img": "https://flagpedia.net/data/flags/w702/dk.png", "name": "الدنمارك" },

  { "img": "https://flagpedia.net/data/flags/w702/dj.png", "name": "جيبوتي" },
  { "img": "https://flagpedia.net/data/flags/w702/do.png", "name": "جمهورية الدومينيكان" },
  { "img": "https://flagpedia.net/data/flags/w702/ec.png", "name": "الإكوادور" },
  { "img": "https://flagpedia.net/data/flags/w702/eg.png", "name": "مصر" },
  { "img": "https://flagpedia.net/data/flags/w702/sv.png", "name": "السلفادور" },
  { "img": "https://flagpedia.net/data/flags/w702/et.png", "name": "إثيوبيا" },
  { "img": "https://flagpedia.net/data/flags/w702/fi.png", "name": "فنلندا" },
  { "img": "https://flagpedia.net/data/flags/w702/fr.png", "name": "فرنسا" },
  { "img": "https://flagpedia.net/data/flags/w702/ga.png", "name": "الغابون" },
  { "img": "https://flagpedia.net/data/flags/w702/de.png", "name": "ألمانيا" },

  { "img": "https://flagpedia.net/data/flags/w702/gh.png", "name": "غانا" },
  { "img": "https://flagpedia.net/data/flags/w702/gr.png", "name": "اليونان" },
  { "img": "https://flagpedia.net/data/flags/w702/gt.png", "name": "غواتيمالا" },
  { "img": "https://flagpedia.net/data/flags/w702/ht.png", "name": "هايتي" },
  { "img": "https://flagpedia.net/data/flags/w702/hn.png", "name": "هندوراس" },
  { "img": "https://flagpedia.net/data/flags/w702/hu.png", "name": "المجر" },
  { "img": "https://flagpedia.net/data/flags/w702/is.png", "name": "آيسلندا" },
  { "img": "https://flagpedia.net/data/flags/w702/in.png", "name": "الهند" },
  { "img": "https://flagpedia.net/data/flags/w702/id.png", "name": "إندونيسيا" },
  { "img": "https://flagpedia.net/data/flags/w702/ir.png", "name": "إيران" },

  { "img": "https://flagpedia.net/data/flags/w702/iq.png", "name": "العراق" },
  { "img": "https://flagpedia.net/data/flags/w702/ie.png", "name": "أيرلندا" },
  { "img": "https://flagpedia.net/data/flags/w702/il.png", "name": "إسرائيل" },
  { "img": "https://flagpedia.net/data/flags/w702/it.png", "name": "إيطاليا" },
  { "img": "https://flagpedia.net/data/flags/w702/jm.png", "name": "جامايكا" },
  { "img": "https://flagpedia.net/data/flags/w702/jp.png", "name": "اليابان" },
  { "img": "https://flagpedia.net/data/flags/w702/jo.png", "name": "الأردن" },
  { "img": "https://flagpedia.net/data/flags/w702/kz.png", "name": "كازاخستان" },
  { "img": "https://flagpedia.net/data/flags/w702/ke.png", "name": "كينيا" },
  { "img": "https://flagpedia.net/data/flags/w702/kw.png", "name": "الكويت" },

  { "img": "https://flagpedia.net/data/flags/w702/lb.png", "name": "لبنان" },
  { "img": "https://flagpedia.net/data/flags/w702/ly.png", "name": "ليبيا" },
  { "img": "https://flagpedia.net/data/flags/w702/my.png", "name": "ماليزيا" },
  { "img": "https://flagpedia.net/data/flags/w702/mx.png", "name": "المكسيك" },
  { "img": "https://flagpedia.net/data/flags/w702/ma.png", "name": "المغرب" },
  { "img": "https://flagpedia.net/data/flags/w702/np.png", "name": "نيبال" },
  { "img": "https://flagpedia.net/data/flags/w702/nl.png", "name": "هولندا" },
  { "img": "https://flagpedia.net/data/flags/w702/nz.png", "name": "نيوزيلندا" },
  { "img": "https://flagpedia.net/data/flags/w702/ng.png", "name": "نيجيريا" },
  { "img": "https://flagpedia.net/data/flags/w702/kp.png", "name": "كوريا الشمالية" },

  { "img": "https://flagpedia.net/data/flags/w702/no.png", "name": "النرويج" },
  { "img": "https://flagpedia.net/data/flags/w702/om.png", "name": "عُمان" },
  { "img": "https://flagpedia.net/data/flags/w702/pk.png", "name": "باكستان" },
  { "img": "https://flagpedia.net/data/flags/w702/pa.png", "name": "بنما" },
  { "img": "https://flagpedia.net/data/flags/w702/pe.png", "name": "بيرو" },
  { "img": "https://flagpedia.net/data/flags/w702/ph.png", "name": "الفلبين" },
  { "img": "https://flagpedia.net/data/flags/w702/pl.png", "name": "بولندا" },
  { "img": "https://flagpedia.net/data/flags/w702/pt.png", "name": "البرتغال" },
  { "img": "https://flagpedia.net/data/flags/w702/qa.png", "name": "قطر" },
  { "img": "https://flagpedia.net/data/flags/w702/ro.png", "name": "رومانيا" },

  { "img": "https://flagpedia.net/data/flags/w702/ru.png", "name": "روسيا" },
  { "img": "https://flagpedia.net/data/flags/w702/sa.png", "name": "السعودية" },
  { "img": "https://flagpedia.net/data/flags/w702/sn.png", "name": "السنغال" },
  { "img": "https://flagpedia.net/data/flags/w702/rs.png", "name": "صربيا" },
  { "img": "https://flagpedia.net/data/flags/w702/sg.png", "name": "سنغافورة" },
  { "img": "https://flagpedia.net/data/flags/w702/so.png", "name": "الصومال" },
  { "img": "https://flagpedia.net/data/flags/w702/za.png", "name": "جنوب إفريقيا" },
  { "img": "https://flagpedia.net/data/flags/w702/kr.png", "name": "كوريا الجنوبية" },
  { "img": "https://flagpedia.net/data/flags/w702/es.png", "name": "إسبانيا" },
  { "img": "https://flagpedia.net/data/flags/w702/lk.png", "name": "سريلانكا" },

  { "img": "https://flagpedia.net/data/flags/w702/sd.png", "name": "السودان" },
  { "img": "https://flagpedia.net/data/flags/w702/se.png", "name": "السويد" },
  { "img": "https://flagpedia.net/data/flags/w702/ch.png", "name": "سويسرا" },
  { "img": "https://flagpedia.net/data/flags/w702/sy.png", "name": "سوريا" },
  { "img": "https://flagpedia.net/data/flags/w702/th.png", "name": "تايلاند" },
  { "img": "https://flagpedia.net/data/flags/w702/tn.png", "name": "تونس" },
  { "img": "https://flagpedia.net/data/flags/w702/tr.png", "name": "تركيا" },
  { "img": "https://flagpedia.net/data/flags/w702/ua.png", "name": "أوكرانيا" },
  { "img": "https://flagpedia.net/data/flags/w702/ae.png", "name": "الإمارات العربية المتحدة" },
  { "img": "https://flagpedia.net/data/flags/w702/gb.png", "name": "المملكة المتحدة" }
]
